### ISSUE TITLE
[P2][Debt] No web lane and no browser test, so nothing about the web platform is verified

### ISSUE THREAD

**Issue by shimakaze09** [shimakaze09/Engine#652]
### Kind

Verification infrastructure gap

### Area

CI / runtime

### Problem

The engine targets six platforms per [0015](../blob/claude/kind-pasteur-r90pip/docs/decisions/0015-commercial-anime-engine-on-six-platforms.md), one of which is the browser. Nothing about that target is verified: `.github/workflows/ci.yml` has no emscripten lane, and there is no emscripten or browser test anywhere under `tests/`.

So every web-specific code path is unproven by construction. `ENGINE_PLATFORM_WEB` gates real behaviour — the RAF main loop (`runtime/src/engine.cpp:371-379`), the lifecycle shutdown inside `web_frame` (`:345-354`), and the frame pacing that is compiled out (`runtime/src/engine_pipeline.cpp:2059-2060`) — and none of it is compiled in CI, let alone run.

### Why it is filed now

It is the reason **#341** cannot close. That P1's fix landed and its host-side equivalent is proven by `engine_integration_engine_bootstrap_rollback`, but its stated regression is "browser tests for maxFrames=1, quit and injected fatal stage", which has nowhere to run. Holding a P1 open for missing infrastructure, without saying so, is how a tracker stops being readable.

It is also a standing risk rather than one issue's problem: web paths can rot silently, and the first person to discover it will be whoever tries to ship to the browser.

### Intended result

A web lane that at minimum **builds** under emscripten in CI, so the platform's code paths cannot break unnoticed; and, where feasible, a headless-browser run of a small scene that asserts the lifecycle closes every tier and a second bootstrap sees no stale state.

### Scope

1. An emscripten build lane in CI (emsdk, `ENGINE_TARGET_PLATFORM=Web`), compile-only to start. This alone catches the majority of rot, since the web paths are currently never compiled by any lane.
2. A headless-browser smoke run (Playwright is already available in the container image) loading the built page, running a bounded number of frames, and asserting the console reports a clean shutdown.
3. Once (2) exists, the three cases #341 asks for: `maxFrames=1`, quit, and an injected fatal stage — then #341 closes on its own contract.

### Acceptance

- The web lane fails when a `ENGINE_PLATFORM_WEB` path stops compiling, demonstrated by a deliberate break.
- The smoke run fails when the lifecycle shutdown is removed from `web_frame`, which is the red-on-base demonstration #341 needs.

### Non-goals

Full parity of the GPU suite in a browser; WebGL capture comparison; performance numbers from a browser.

### Additional context

P2 rather than P1: no user-visible defect is known to be hiding here, but a whole declared platform is unverified, and one P1 is blocked on it. It is not P3 because the blocked P1 and the six-platform goal both make it more than hygiene.

---
🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01J2Gp9YvXUDigxRLpqAZg78

**Comment by shimakaze09** [comment]
PR #691 (head `d59c06de`) delivers all three scope items and closes this issue when it merges.

1. **Emscripten lane.** Job `web (Emscripten)` builds with emsdk 6.0.10, checked out at its tag commit `a2b92777` (`ENGINE_TARGET_PLATFORM=Web`). The pages package the Linux Release lane's shader cook, passed as a 1-day artifact. It restores the existing Linux sources cache and saves none of its own. "Required CI quality gate" needs it.
   - **Acceptance: fails when a web path stops compiling.** With `web_frame`'s `emscripten_cancel_main_loop()` given a bogus argument, the native build still links `engine_runtime` (rc 0, the line is compiled out). The web build fails: `runtime/src/engine.cpp:396:5: error: no matching function for call to 'emscripten_cancel_main_loop'`. Local, Windows 11, 2026-09-23. Reverted.
2. **Headless-browser smoke.** `engine_web_page_boots` loads the shipped `engine_editor_app.html` through its share shell and runs 120 animation frames. It fails on any page error, WebGL error or engine Error line. `engine_web_lifecycle_frames` runs a bounded 30-frame loop and asserts every tier closes.
3. **#341's cases.** `engine_web_lifecycle_max_frames_1`, `_quit` and `_fatal_stage`. Evidence and red-on-base are in #341.
   - **Acceptance: fails when the lifecycle shutdown is removed from `web_frame`.** All four lifecycle tests fail with `tiers still open after its loop ended`.

**CI evidence.** [Run 35847381024](https://github.com/shimakaze09/Engine/actions/runs/35847381024), 2026-09-23: `web (Emscripten)` passed 5/5 browser tests, and all 17 jobs are green.

**What the lane found.** The shipped page was broken on `main`. #691 fixes each defect with its own commit and a test that fails without it:
- an essl compile abort;
- shadow-array creation failing without texture arrays;
- a pthread-pool deadlock on a short run;
- a missing `HEAPF32` export;
- an unhandled AudioContext rejection;
- WebGL rejecting pbr/deferred draws.

Out of scope and filed separately:
- #690: the browser page has no cascade or spot shadows, because bgfx exposes no texture arrays under Emscripten.
- #689: `on_begin_play` cannot spawn. Not web-specific.

**Non-goals held.** There's no GPU-suite parity and no image comparison. The lane proves the page runs without errors, not what it shows.

---
_Generated by [Claude Code](https://claude.ai/code)_
